# Working with Categorical and Numeric Data
##### Using Label Encoding and One Hot Encoding for categorical data; Apply scaling to numeric data

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

### Sample data representing student data and exam scores
Download link: http://roycekimmons.com/system/generate_data.php?dataset=exams&n=100

In [3]:
exam_data = pd.read_csv('../data/exams.csv', quotechar='"')
exam_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group E,associate's degree,standard,completed,79,75,81
1,female,group C,associate's degree,free/reduced,none,56,65,64
2,male,group D,bachelor's degree,standard,none,86,68,74
3,female,group A,bachelor's degree,standard,none,68,78,76
4,female,group D,high school,free/reduced,none,49,68,61
...,...,...,...,...,...,...,...,...
95,female,group A,master's degree,free/reduced,completed,59,76,80
96,female,group D,high school,free/reduced,none,60,62,61
97,female,group C,some college,standard,none,69,82,83
98,male,group D,some high school,standard,none,89,83,79
99,female,group A,master's degree,free/reduced,completed,65,88,88

#### Check out average score for each exam

In [4]:
math_average = exam_data['math score'].mean()
reading_average = exam_data['reading score'].mean()
writing_average = average = exam_data['writing score'].mean()

print('Math Avg: ', math_average)
print('Reading Avg: ', reading_average)
print('Writing Avg: ', writing_average)

Math Avg:  65.06
Reading Avg:  67.28
Writing Avg:  66.47

### Data Standardization:
Apply scaling on the test scores to express them in terms of <b>z-score</b> <br />
Z-score is the expression of a value in terms of the number of standard deviations from the mean <br />
The effect is to give a score which is relative to the the distribution of values for that column

In [6]:
from sklearn import preprocessing

exam_data[['math score']] = preprocessing.scale(exam_data[['math score']])
exam_data[['reading score']] = preprocessing.scale(exam_data[['reading score']])
exam_data[['writing score']] = preprocessing.scale(exam_data[['writing score']])

In [7]:
exam_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group E,associate's degree,standard,completed,0.994557,0.574138,1.049901
1,female,group C,associate's degree,free/reduced,none,-0.646391,-0.169564,-0.178476
2,male,group D,bachelor's degree,standard,none,1.493976,0.053547,0.544099
3,female,group A,bachelor's degree,standard,none,0.209756,0.797248,0.688613
4,female,group D,high school,free/reduced,none,-1.145810,0.053547,-0.395248
5,male,group D,some high school,free/reduced,none,-1.145810,-1.508227,-1.840397
6,male,group C,some high school,standard,none,1.565321,0.797248,0.255069
7,male,group C,associate's degree,standard,none,0.637829,0.945989,0.688613
8,female,group B,some high school,standard,none,-1.074464,-1.731338,-1.334595
9,male,group A,some college,standard,none,-1.787920,-3.293112,-3.141031
10,female,group D,some high school,standard,completed,0.209756,0.574138,0.760871
11,female,group B,associate's degree,standard,none,1.208594,1.466580,1.483445
12,male,group A,some high school,standard,none,1.279939,0.871619,0.688613
13,female,group B,high school,standard,completed,-0.646391,-0.095194,0.544099
14,male,group C,high school,standard,none,-0.218317,-0.838896,-0.973308
15,female,group B,master's degree,standard,none,-0.575045,0.053547,0.327326
16,male,group B,high school,standard,none,0.851866,-0.615785,-0.901050
17,female,group C,some college,free/reduced,completed,-1.145810,-0.392675,-0.756535
18,female,group B,associate's degree,standard,completed,-0.432354,-0.020824,0.327326
19,male,group A,some college,free/reduced,none,-0.146972,-1.136376,-1.045565
20,male,group B,some college,standard,none,-0.075626,-0.467045,-0.395248
21,female,group C,master's degree,free/reduced,none,-0.789082,-0.243934,-0.539763
22,male,group C,high school,standard,completed,1.636667,1.020359,1.194416
23,male,group C,associate's degree,standard,none,-0.218317,-0.913266,-1.045565
24,male,group D,bachelor's degree,free/reduced,none,-0.931773,-0.095194,-0.756535
25,male,group B,high school,standard,completed,1.850704,1.392210,1.122158
26,female,group C,high school,free/reduced,none,-2.287338,-1.880078,-1.840397
27,female,group C,associate's degree,free/reduced,none,0.067065,0.648508,0.471841
28,female,group B,some high school,standard,none,-2.287338,-1.508227,-1.984912
29,male,group E,some college,free/reduced,completed,0.637829,0.425397,0.688613
...,...,...,...,...,...,...,...,...
70,female,group E,bachelor's degree,free/reduced,completed,0.209756,0.945989,0.905386
71,male,group C,some high school,free/reduced,none,-0.860427,-1.210747,-1.479110
72,female,group C,some high school,standard,completed,-0.646391,-0.838896,-0.901050
73,male,group C,high school,free/reduced,completed,-0.146972,-0.467045,-0.828793
74,male,group D,some high school,standard,completed,-0.361008,-0.318304,-0.684278
75,male,group D,master's degree,standard,completed,0.352447,0.127917,0.471841
76,male,group B,some college,standard,none,-0.075626,-0.243934,-0.467506
77,female,group C,associate's degree,free/reduced,completed,-0.931773,0.425397,0.110554
78,female,group C,associate's degree,standard,completed,-0.289663,0.648508,0.905386
79,female,group B,high school,standard,completed,-0.146972,0.202287,0.833128
80,male,group D,some college,standard,none,0.637829,0.351027,0.544099
81,male,group C,bachelor's degree,standard,completed,1.279939,1.169099,1.411188
82,male,group C,master's degree,free/reduced,none,0.138410,-0.467045,-0.756535
83,male,group B,high school,free/reduced,completed,-1.288501,-0.690155,-0.973308
84,female,group C,master's degree,free/reduced,none,-0.218317,-0.318304,0.399584
85,male,group C,associate's degree,standard,none,-0.503700,-0.838896,-0.178476
86,female,group B,some college,standard,completed,-0.361008,0.574138,0.544099
87,male,group B,high school,free/reduced,completed,-0.075626,-0.690155,-0.178476
88,female,group D,some college,standard,none,0.923211,1.094729,1.122158
89,female,group C,high school,free/reduced,completed,-0.575045,-0.169564,-0.033961
90,male,group C,high school,standard,completed,2.278777,1.764061,2.133762
91,male,group C,high school,free/reduced,completed,0.495138,0.053547,-0.033961
92,female,group D,some college,standard,none,0.423793,0.722878,0.688613
93,female,group A,master's degree,free/reduced,completed,-1.502537,-0.764526,-0.322991
94,female,group B,some college,standard,none,0.281101,1.615320,1.194416
95,female,group A,master's degree,free/reduced,completed,-0.432354,0.648508,0.977643
96,female,group D,high school,free/reduced,none,-0.361008,-0.392675,-0.395248
97,female,group C,some college,standard,none,0.281101,1.094729,1.194416
98,male,group D,some high school,standard,none,1.708013,1.169099,0.905386
99,female,group A,master's degree,free/reduced,completed,-0.004281,1.540950,1.555703

#### Explore averages after scaling

In [7]:
math_average = exam_data['math score'].mean()
reading_average = exam_data['reading score'].mean()
writing_average = average = exam_data['writing score'].mean()

print('Math Avg: ', math_average)
print('Reading Avg: ', reading_average)
print('Writing Avg: ', writing_average)

Math Avg:  -1.5693175925424186e-16
Reading Avg:  -1.0880185641326534e-16
Writing Avg:  8.881784197001253e-17

### Label Encoding:
Convert text values to numbers. These can be used in the following situations:
* There are only two values for a column in your data. The values will then become 0/1 - effectively a binary representation
* The values have relationship with each other where comparisons are meaningful (e.g. low<medium<high)

In [8]:
le = preprocessing.LabelEncoder()
exam_data['gender'] = le.fit_transform(exam_data['gender'].astype(str))

In [9]:
exam_data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,1,group E,associate's degree,standard,completed,0.994557,0.574138,1.049901
1,0,group C,associate's degree,free/reduced,none,-0.646391,-0.169564,-0.178476
2,1,group D,bachelor's degree,standard,none,1.493976,0.053547,0.544099
3,0,group A,bachelor's degree,standard,none,0.209756,0.797248,0.688613
4,0,group D,high school,free/reduced,none,-1.145810,0.053547,-0.395248

In [10]:
le.classes_

array(['female', 'male'], dtype=object)

### One-Hot Encoding:
* Use when there is no meaningful comparison between values in the column
* Creates a new column for each unique value for the specified feature in the data set

In [11]:
pd.get_dummies(exam_data['race/ethnicity'])

    group A  group B  group C  group D  group E
0     False    False    False    False     True
1     False    False     True    False    False
2     False    False    False     True    False
3      True    False    False    False    False
4     False    False    False     True    False
..      ...      ...      ...      ...      ...
95     True    False    False    False    False
96    False    False    False     True    False
97    False    False     True    False    False
98    False    False    False     True    False
99     True    False    False    False    False

[100 rows x 5 columns]

#### Include the dummy columns in our data set

In [12]:
exam_data = pd.get_dummies(exam_data, columns=['race/ethnicity'])

In [13]:
exam_data

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E
0,1,associate's degree,standard,completed,0.994557,0.574138,1.049901,False,False,False,False,True
1,0,associate's degree,free/reduced,none,-0.646391,-0.169564,-0.178476,False,False,True,False,False
2,1,bachelor's degree,standard,none,1.493976,0.053547,0.544099,False,False,False,True,False
3,0,bachelor's degree,standard,none,0.209756,0.797248,0.688613,True,False,False,False,False
4,0,high school,free/reduced,none,-1.145810,0.053547,-0.395248,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,master's degree,free/reduced,completed,-0.432354,0.648508,0.977643,True,False,False,False,False
96,0,high school,free/reduced,none,-0.361008,-0.392675,-0.395248,False,False,False,True,False
97,0,some college,standard,none,0.281101,1.094729,1.194416,False,False,True,False,False
98,1,some high school,standard,none,1.708013,1.169099,0.905386,False,False,False,True,False
99,0,master's degree,free/reduced,completed,-0.004281,1.540950,1.555703,True,False,False,False,False

#### Apply one-hot-encoding for remaining non-numeric features

In [14]:
exam_data = pd.get_dummies(exam_data, columns=['parental level of education', 
                                               'lunch', 
                                               'test preparation course'])

#### The data is now ready to be used to train a model

In [15]:
exam_data.head()

,gender,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_free/reduced,lunch_standard,test preparation course_completed,test preparation course_none
0,1,0.994557,0.574138,1.049901,False,False,False,False,True,True,False,False,False,False,False,False,True,True,False
1,0,-0.646391,-0.169564,-0.178476,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
2,1,1.493976,0.053547,0.544099,False,False,False,True,False,False,True,False,False,False,False,False,True,False,True
3,0,0.209756,0.797248,0.688613,True,False,False,False,False,False,True,False,False,False,False,False,True,False,True
4,0,-1.145810,0.053547,-0.395248,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True